// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WolfLeash.Database;

#nullable disable

namespace WolfLeash.Migrations
{
    [DbContext(typeof(WolfLeashDbContext))]
    [Migration("20251118201605_ChangedClientsIdType")]
    partial class ChangedClientsIdType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("WolfLeash.Database.Model.Client", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("WolfLeash.Database.Model.DbApp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Av1_gst_pipeline")
                        .HasColumnType("TEXT");

                    b.Property<string>("H264_gst_pipeline")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hevc_gst_pipeline")
                        .HasColumnType("TEXT");

                    b.Property<string>("IconPngPath")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Opus_gst_pipeline")
                        .HasColumnType("TEXT");

                    b.Property<string>("RenderNode")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("RunnerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("StartAudioServer")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("StartVirtualCompositor")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("SupportHdr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppId")
                        .IsUnique();

                    b.HasIndex("RunnerId");

                    b.ToTable("Apps", (string)null);
                });

            modelBuilder.Entity("WolfLeash.Database.Model.Runner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseCreateJson")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Devices")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Env")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Mounts")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Ports")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Runners", (string)null);
                });

            modelBuilder.Entity("WolfLeash.Database.Model.DbApp", b =>
                {
                    b.HasOne("WolfLeash.Database.Model.Runner", "Runner")
                        .WithMany()
                        .HasForeignKey("RunnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Runner");
                });
#pragma warning restore 612, 618
        }
    }
}
